#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7

bspc config focused_border_color \#444444
bspc config window_gap          15
bspc config top_monocle_padding 10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config initial_polarity first_child # make new windows go on top of the tree
bspc config automatic_scheme spiral
bspc config ignore_ewmh_focus true # don't jump to browser when clicking links

bspc rule -a Zathura state=tiled

## Autostart ##
$HOME/.scripts/randwal & # script for random wallpaper with wpgtk
betterlockscreen -l blur &
picom &
$HOME/.config/polybar/launch.sh
xsetroot -cursor_name left_ptr &
unclutter &
xset -b & # turns motherboard speaker off
setxkbmap -layout pl &
dunst &
brave &
discord &
pgrep bspswallow || bspswallow &

if ! pgrep -x "redshift" > /dev/null 	#
then																	# Starts redshift for location of Wroclaw 
	redshift -l 51:17 &									# (if not already running)
fi																		#

# MPD daemon start (if no other user instance exists)
[ ! -s ~/.config/mpd/pid ] && mpd &


## Windows rules
bspc rule -a '*' border=off

bspc rule -a Alacritty state=tiled border=on
bspc rule -a Pcmanfm state=tiled border=on
bspc rule -a rpv state=pseudo-tiled
bspc rule -a Brave-browser desktop='^2' state=tiled layout=monocle
bspc rule -a discord desktop=3 state=tiled layout=monocle
bspc desktop '^2' -l monocle
bspc desktop '^3' -l monocle


## Focused window on top
while :; do
        bspc subscribe --count 1 node_focus > /dev/null || break
        bspc node focused --layer above
        bspc node focused --layer normal
done

## Border only on focused window
while bspc subscribe -c 1 node_focus; do
    bspc config border_width 0
    bspc config -n focused border_width 1
done
