#!/bin/bash

if [ -z "$1" ]; then
	files=($HOME/Pictures/Wallpapers/*)
	path=${files[RANDOM % ${#files[@]}]}
else
	path=$(readlink -f $1)
fi

echo $path

feh --bg-fill --no-fehbg $path
wpg -s $path
#wal -i $path

## Update bspwm colors
. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color0"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color2"
bspc config presel_feedback_color "$color1"

betterlockscreen -u $path --fx blur
